@startuml
class com.formdev.flatlaf.FlatIntelliJLaf
class java.util.logging.Level
class java.util.logging.Logger
class javax.swing.UIManager
class javax.swing.UnsupportedLookAndFeelException
class main.App
class views.Main_views
main.App ..> com.formdev.flatlaf.FlatIntelliJLaf
main.App ..> java.util.logging.Level
main.App ..> java.util.logging.Logger
main.App ..> javax.swing.UIManager
main.App ..> javax.swing.UnsupportedLookAndFeelException
main.App ..> views.Main_views
@enduml